---
- name: Playbook_main
  hosts: localhost
  become: true
  vars:
    nginx_container_name: nginx-container
    nginx_image_name: nginx:latest
    nginx_container_port: 80
    nginx_host_port: 8080
    nginx_server_name: my_nginx_server
    nginx_conf_path: /etc/nginx/conf.d/my-apache-container.conf
    apache_container_name: apache-container
    apache_image_name: httpd:latest
    apache_container_port: 80
    apache_host_port: 8081
    ftp_password: passwd
    ftp_user: admin
    ftp_directory: /var/ftp

  tasks:
  - name: Install Docker
    apt:
      name: docker.io

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Verify NGINX is running
    wait_for:
      host: localhost
      port: "{{ nginx_host_port }}"
      delay: 5
      timeout: 60
      state: started

  - name: Pull NGINX Docker image
    docker_image:
      name: "{{ nginx_image_name }}"
      source: pull

  - name: Start NGINX container
    docker_container:
      name: "{{ nginx_container_name }}"
      image: "{{ nginx_image_name }}"
      ports:
        - "{{ nginx_host_port }}:{{ nginx_container_port }}"
      volumes:
        - "{{ nginx_conf_path }}:/etc/nginx/conf.d/default.conf:ro"
      restart_policy: always

  - name: Install Apache Docker image
    docker_image:
      name: "{{ apache_image_name }}"
      source: pull

  - name: Start Apache container
    docker_container:
      name: "{{ apache_container_name }}"
      image: "{{ apache_image_name }}"
      ports:
        - "{{ apache_host_port }}:{{ apache_container_port }}"
      restart_policy: always

  - name: Verify Apache is running
    wait_for:
      host: localhost
      port: "{{ apache_host_port }}"
      delay: 5
      timeout: 60
      state: started
