---
- name: Playbook_main
  hosts: localhost
  become: true
  vars:
    nginx_container_name: nginx-container
    nginx_image_name: nginx:latest
    nginx_container_port: 80
    nginx_host_port: 8080
    nginx_server_name: nginx-server
    nginx_conf_path: /etc/nginx/conf.d/my-apache-container.conf
    apache_container_name: apache-container
    apache_image_name: httpd:latest
    apache_container_port: 80
    apache_host_port: 8081
    ftp_container_name: ftp_server
    ftp_container_image: fauria/vsftpd
    ftp_container_port: "21:21"
    ftp_user: admin
    ftp_password: password
    ftp_directory: /var/ftp

  tasks:
  - name: Install Docker
    apt:
      name: docker.io

  - name: Install Apache Docker image
    docker_image:
      name: "{{ apache_image_name }}"
      source: pull

  - name: Start Apache container
    docker_container:
      name: "{{ apache_container_name }}"
      image: "{{ apache_image_name }}"
      ports:
        - "{{ apache_host_port }}:{{ apache_container_port }}"
      restart_policy: always

  - name: Verify Apache is running
    wait_for:
      host: localhost
      port: "{{ apache_host_port }}"
      delay: 5
      timeout: 60
      state: started

#  - name: Verify NGINX is running
#    wait_for:
#      host: localhost
#      port: "{{ nginx_host_port }}"
#      delay: 5
#      timeout: 60
#      state: started

#  - name: Pull NGINX Docker image
#    docker_image:
#      name: "{{ nginx_image_name }}"
#      source: pull

#  - name: Start NGINX container
#    docker_container:
#      name: "{{ nginx_container_name }}"
#      image: "{{ nginx_image_name }}"
#      ports:
#        - "{{ nginx_host_port }}:{{ nginx_container_port }}"
     # volumes:
     #  - "{{ nginx_conf_path }}:/etc/nginx/conf.d/default.conf:ro"
#      state: started

 # - name: Configure NGINX reverse proxy
 #   copy:
 #     dest: "{{ nginx_conf_path }}"
 #     content: |
 #       server {
 #         listen 80;
 #         server_name {{ nginx_server_name }};

 #        location / {
 #          proxy_pass http://localhost:{{ apache_container_port }};
 #           proxy_set_header Host $host;
 #           proxy_set_header X-Real-IP $remote_addr;
 #           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  - name: FTP server docker container
    docker_container:
      name: "{{ ftp_container_name }}"
      image: "{{ ftp_container_image }}"
      state: started
      published_ports: "{{ ftp_container_port }}"
      restart_policy: always
      env:
        FTP_user: "{{ ftp_user }}"
        FTP_password: "{{ ftp_password }}"

#  - name: Configure FTP access
#     lineinfile:
#      path: /etc/vsftpd.conf
#      line: |
#        local_enable=YES
#        write_enable=YES
#        local_umask=022
#        chroot_local_user=YES
#        allow_writeable_chroot=YES
#      state: present

#  - name: Configure FTP user access
#      shell: |
#      sudo htpasswd -b -c /etc/ftpd.passwd {{ ftp_user }} {{ ftp_password }}
#      args:
#      executable: /bin/bash

  - name: Restart FTP server
    docker_container:
      name: "{{ ftp_container_name}}"
      state: started
