---
- hosts: localhost
  collections:
     - community.docker
  become: true
 
  vars:
    container_name: nginx_server
    image_name: nginx:latest
    container_port: 21
    host_port: 20
    ftp_user: "majnu"
    ftp_pass: "majnu"
 
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags:
        - docker
 
    - name: Start Docker service
      service:
        name: docker
        state: started
      tags:
        - docker
 
    - name: start ftpserver container
      docker_container:
        name: ftp_server
        image: arth2001/image_ftpserver
        state: started
        restart_policy: always
        command: /bin/bash
        tty: true
        detach: true
        interactive: true
        ports:
           - "{{ host_port }}:{{ container_port }}"
